### ISSUE TITLE
decodeAudioData example broken

### ISSUE THREAD

**Issue by a2sheppy** [mdn/webaudio-examples#1]
Due to content security policy issues, the example is not able to load viper.ogg.

https://github.com/mdn/webaudio-examples/tree/master/decode-audio-data

**Comment by chrisdavidmills** [comment]
I've just tested this; WFM in both Fx and Chrome?

**Comment by StTronn** [comment]
I am getting the following error in the example which might be related to this issue  
```
from origin 'null' has been blocked by CORS policy:
Cross origin requests are only supported for protocol schemes:
http, data, chrome, chrome-extension, https.
```
does anyone happen to know a workaround to this

**Comment by Leokuma** [comment]
@StTronn Ideally you should have a web server running (like Apache) and then access the example through `localhost` or `127.0.0.1` rather than opening the local file directly from the filesystem. Let me know if you have trouble doing that.

[This article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) is about JS modules, but the problem is very similar and may help you understand it:

> If you try to load the HTML file locally (i.e. with a file:// URL), you'll run into CORS errors due to JavaScript module security requirements. You need to do your testing through a server.
